/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function dummyTest(): boolean
export function configatronInitializer(): void
export function processPath(path: string): void
export class Blueprint {
  constructor()
  useCurrentTime(): string
  title(msg: string): void
  log(msg: string): void
  error(msg: string): void
  warn(msg: string): void
  info(msg: string): void
  bold(msg: string): string
}
export class Configatron {
  constructor()
  collectFromJs(keys: Array<string>): string
}
