/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function processPath(path: string): void
export function dummySum(a: number, b: number): string
export class Blueprint { }
