use super::{g3css_elements::G3cssElements, g3css_panoramic::G3cssPanoramic};

/// Enum representing different properties of class elements in the G3CSS framework
#[derive(PartialEq, Debug, Clone)]
pub enum G3cssClass {
    ClassName(String),
    Inherits(String),
    Important(String),
    Properties(Vec<G3cssElements>),
    Hover(Vec<G3cssElements>),
    Active(Vec<G3cssElements>),
    Focus(Vec<G3cssElements>),
    FirstChild(Vec<G3cssElements>),
    LastChild(Vec<G3cssElements>),
    FirstOfType(Vec<G3cssElements>),
    LastOfType(Vec<G3cssElements>),
    OnlyChild(Vec<G3cssElements>),
    OnlyOfType(Vec<G3cssElements>),
    TargetPseudoClass(Vec<G3cssElements>),
    Visited(Vec<G3cssElements>),
    Checked(Vec<G3cssElements>),
    Disabled(Vec<G3cssElements>),
    Enabled(Vec<G3cssElements>),
    ReadOnly(Vec<G3cssElements>),
    ReadWrite(Vec<G3cssElements>),
    PlaceholderShown(Vec<G3cssElements>),
    Valid(Vec<G3cssElements>),
    Invalid(Vec<G3cssElements>),
    Required(Vec<G3cssElements>),
    Optional(Vec<G3cssElements>),
    Fullscreen(Vec<G3cssElements>),
    FocusWithin(Vec<G3cssElements>),
    FirstLine(Vec<G3cssElements>),
    FirstLetter(Vec<G3cssElements>),
    Before(Vec<G3cssElements>),
    After(Vec<G3cssElements>),
    OutOfRange(Vec<G3cssElements>),
    Root(Vec<G3cssElements>),
    FirstPage(Vec<G3cssElements>),
    LeftPage(Vec<G3cssElements>),
    RightPage(Vec<G3cssElements>),
    Empty(Vec<G3cssElements>),
    PanoramicViewer(Vec<Vec<G3cssPanoramic>>),
}
